import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/header'
import HowItWork from '../components/how-it-works'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Clean Creation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header/>
        <HowItWork/>
      </main>
    </div>
  )
}

export default Home
